<?php
/**
 * Copyright (c) 2008–2026 Loic Richard
 *
 * Licensed under AGPLv3 or commercial license.
 * See LICENSE file.
 */
namespace ClicShopping\Apps\Configuration\ChatGpt\Classes\ClicShoppingAdmin;


use ClicShopping\OM\Registry;
use ClicShopping\Apps\Configuration\ChatGpt\ChatGpt;
use ClicShopping\Apps\Configuration\ChatGpt\Classes\ClicShoppingAdmin\Gpt;
use ClicShopping\AI\Infrastructure\Schema\SchemaEmbedder;


class Cron {
  private mixed $app;
  private mixed $lang;
  /**
   * Class constructor.
   *
   * Initializes the ChatGpt instance in the Registry if it doesn't already exist,
   * and loads the necessary definitions for the application.
   *
   * @return void
   */
  public function __construct()
  {
    if (!Registry::exists('ChatGpt')) {
      Registry::set('ChatGpt', new ChatGpt());
    }

    $this->app = Registry::get('ChatGpt');
    $this->lang = Registry::get('Language');
  }

/**
 * Updates the embedding page manager for a specific language.
 *
 * @param int $language_id The ID of the language to update.
 * @return void
 */
  private function updateAllEmbeddingPageManager(int $language_id): void
  {
    $Qcheck = $this->app->db->prepare('select pm.pages_id,
                                             pm.page_type,       
                                             pmd.pages_title,
                                             pmd.pages_html_text,
                                             pmd.page_manager_head_title_tag,
                                             pmd.page_manager_head_desc_tag,
                                             pmd.page_manager_head_keywords_tag,
                                             pmd.language_id
                                       from  :table_pages_manager pm,
                                             :table_pages_manager_description pmd
                                       where pm.pages_id = pmd.pages_id 
                                       and pmd.language_id = :language_id
                                       and pm.page_type = 4
                                      ');

    $Qcheck->bindInt(':language_id', $language_id);
    $Qcheck->execute();

    $check_array = $Qcheck->fetchAll();
    $embedder = new PageManagerEmbedder();

    foreach ($check_array as $item) {
      $Qcheck = $this->app->db->prepare('select id,
                                                entity_id
                                         from :table_pages_manager_embedding
                                         where entity_id = :entity_id
                                        ');
      $Qcheck->bindInt(':entity_id', $item['pages_id']);
      $Qcheck->execute();

      // Same builder as the PageManager Save hook: one format for the whole store.
      if ($Qcheck->fetch() === false && !$embedder->embed($item, false)) {
        error_log("Cron PageManager: Failed to save embeddings for page {$item['pages_id']}");
      }
    }
  }

  /**
   * Updates the page manager embeddings for every active language, then syncs
   * the schema embedding store.
   *
   * Only the page manager (kept here — not an e-commerce entity) and the
   * schema sync remain in this class. Categories, manufacturers, products,
   * reviews and suppliers embeddings are now generated by the Ecommerce app's
   * EmbeddingCronRunner (Shop/Cronjob/Process dispatch).
   *
   * @return void
   * @throws \JsonException
   */
  public function updateAllEmbeddings(): void
  {
    $language_array = $this->lang->getLanguages();

    foreach ($language_array as $value) {
      $this->updateAllEmbeddingPageManager($value['id']);
    }

    $this->updateSchemaEmbeddings();
  }

  /**
   * Keeps the schema embedding store in sync with the database schema.
   *
   * Entity embeddings follow the data, this one follows the schema: without it any
   * table added, dropped or re-commented degrades schema retrieval silently.
   *
   * @return void
   */
  private function updateSchemaEmbeddings(): void
  {
    $stats = (new SchemaEmbedder())->syncAllTables();

    if ($stats['created'] > 0 || $stats['updated'] > 0 || $stats['deleted'] > 0 || $stats['failed'] > 0) {
      error_log("Cron Schema: {$stats['created']} created, {$stats['updated']} updated, {$stats['deleted']} deleted, {$stats['failed']} failed");
    }
  }

  /**
   * Handles the execution of a cron job related to page manager embedding updates.
   *
   * This method checks if GPT functionality is enabled and if OpenAI embedding is enabled.
   * If both conditions are met, it updates the page manager embeddings for each
   * language and syncs the schema embedding store.
   *
   * @return bool|void Returns false if GPT or embedding is disabled, void otherwise
   */
  public function execute()
  {
    if (Gpt::checkGptStatus() === false) {
      return false;
    }

    if (!defined('CLICSHOPPING_APP_CHATGPT_RA_OPENAI_EMBEDDING') || CLICSHOPPING_APP_CHATGPT_RA_OPENAI_EMBEDDING == 'False') {
      return false;
    }

    $this->updateAllEmbeddings();
  }
}
