<?php
/**
 * Copyright (c) 2008–2026 Loic Richard
 *
 * Licensed under AGPLv3 or commercial license.
 * See LICENSE file.
 */

namespace ClicShopping\AI\Security;


use ClicShopping\OM\CLICSHOPPING;
use ClicShopping\OM\Registry;
use DateTime;
use ClicShopping\AI\Security\SecurityLogger;
use ClicShopping\AI\DomainsAI\DomainRegistry;
use ClicShopping\AI\Config\DomainConfig;
use ClicShopping\AI\Config\DomainFields;

/**
 * LlmGuardrails
 *
 * Class for validating LLM responses with domain-specific guardrails.
 * Implements validation heuristics, hallucination detection, and response quality assessment.
 *
 * **Domain-Agnostic Design**: This class adapts to the active domain configuration.
 * When a domain is configured, it loads domain-specific validation rules if available.
 * When no domain is configured, it uses generic validation patterns.
 */

class LlmGuardrails
{
  private const CONFIDENCE_THRESHOLD = 0.75;
  private const MAX_RESPONSE_LENGTH = 8192;
  private const MIN_CONFIDENCE_SCORE = 0.6;

  private const WEIGHTS = [
    'structural' => 0.2,
    'content' => 0.3,
    'hallucination' => 0.3,
    'numerical' => 0.15,
    'sources' => 0.05
  ];
  protected static ?SecurityLogger $securityLogger = null;
  private static mixed $language = null;
  private static bool $debug = false;

  // Configurable weights for overall score calculation
  private static array $suspiciousPatterns = [];
  private static ?array $lastEvaluation = null;

  /**
   * Returns the last evaluation results from checkGuardrails.
   *
   * @return array|null
   */
  public static function getLastEvaluation(): ?array
  {
    return self::$lastEvaluation;
  }

  /**
   * Checks guardrails on the LLM response.
   *
   * Validates the generated answer from the AI against domain-specific guardrails,
   * including structural, business content, hallucination, and numerical checks.
   *
   * **Domain-Aware**: Loads validation rules from domain configuration when available.
   *
   * @param string $question The question asked to the AI
   * @param string $result The response generated by the AI
   * @return array|string Validation results or error message
   */
  public static function checkGuardrails(string $question, string $result, array $groundingMetadata = []): array|string
  {
    self::initLogger();
    $guardrailsValidation = LlmGuardrails::GuardrailsResult($result);

    // Decision based on validation
    switch ($guardrailsValidation['action']) {
      case 'block':
        if (self::$debug) {
          self::$securityLogger->logSecurityEvent('Response blocked by guardrails: ' . json_encode($guardrailsValidation), 'warning');
        }

        return CLICSHOPPING::getDef('error_llm_guardrails_block');
      case 'manual_review':
        if (self::$debug) {
          self::$securityLogger->logSecurityEvent('Response requires manual review: ' . json_encode($guardrailsValidation), 'warning');
        }

        $result = CLICSHOPPING::getDef('error_llm_guardrails_manual_review', ['result' => $result]);
        break;

      case 'allow_with_warning':
        // Do not overwrite $result - the response is already validated
        // The warning is handled by guardrails metrics displayed separately
        break;
    }

    $evaluationResults = LlmResponseEvaluator::evaluateLlmResponse($question, $result, $groundingMetadata);

    self::$lastEvaluation = $evaluationResults;

    return $evaluationResults;
  }

  /**
   * Initializes the security logger if not already done.
   *
   * This method ensures that the SecurityLogger instance is created only once,
   * following the singleton pattern. It is called before any logging operations.
   * Also loads hallucination patterns from the active domain app.
   */
  private static function initLogger(): void
  {
    if (self::$securityLogger === null) {
      self::$securityLogger = new SecurityLogger();
      self::$debug = defined('CLICSHOPPING_APP_CHATGPT_CH_DEBUG') && CLICSHOPPING_APP_CHATGPT_CH_DEBUG === 'True';
    }

    self::$language = Registry::get('Language');

    // Load hallucination patterns from domain app
    self::loadGuardrailsPatterns();
  }

  /**
   * Loads hallucination patterns from the active domain app
   *
   * This method retrieves the active domain app via DomainRegistry and loads
   * hallucination patterns from the domain's HallucinationPatterns class.
   * Falls back to generic patterns if domain config is not available.
   */
  private static function loadGuardrailsPatterns(): void
  {
    // If patterns already loaded, skip
    if (!empty(self::$suspiciousPatterns)) {
      return;
    }

    try {
      // Get DomainRegistry instance
      $registry = DomainRegistry::getInstance();

      // Get active domain app
      $activeApp = $registry->getActiveApp();

      if ($activeApp !== null) {
        // Try to load patterns from domain app
        $appClass = get_class($activeApp);
        $namespace = substr($appClass, 0, strrpos($appClass, '\\'));
        $patternsClass = $namespace . '\\Classes\\ClicShoppingAdmin\\Patterns\\HallucinationPatterns';

        if (class_exists($patternsClass) && method_exists($patternsClass, 'getSuspiciousPatterns')) {
          self::$suspiciousPatterns = $patternsClass::getSuspiciousPatterns();

          if (self::$debug) {
            self::$securityLogger->logSecurityEvent(
              'Loaded ' . count(self::$suspiciousPatterns) . ' hallucination patterns from domain: ' . $appClass,
              'info'
            );
          }

          return;
        }
      }

      // Fallback: Load generic patterns when no domain app is found
      self::$suspiciousPatterns = self::getGenericHallucinationPatterns();

      if (self::$debug) {
        self::$securityLogger->logSecurityEvent(
          'No domain-specific hallucination patterns found, using generic patterns (' . count(self::$suspiciousPatterns) . ' patterns)',
          'info'
        );
      }

    } catch (\Exception $e) {
      // Fallback to generic patterns on error
      self::$suspiciousPatterns = self::getGenericHallucinationPatterns();

      if (self::$debug) {
        self::$securityLogger->logSecurityEvent(
          'Error loading hallucination patterns: ' . $e->getMessage() . ', using generic patterns',
          'warning'
        );
      }
    }
  }

  /**
   * Get generic hallucination patterns for domain-agnostic validation
   *
   * Returns a basic set of hallucination patterns that work across all domains.
   * These patterns detect common hallucination indicators like:
   * - Unrealistic numbers (e.g., "999999999")
   * - Placeholder text (e.g., "Lorem ipsum", "TODO", "FIXME")
   * - Suspicious phrases (e.g., "I don't know", "I cannot", "As an AI")
   *
   * @return array Array of regex patterns for generic hallucination detection
   */
  private static function getGenericHallucinationPatterns(): array
  {
    return [
      '/999999999/',                    // Unrealistic placeholder numbers
      '/lorem ipsum/i',                 // Placeholder text
      '/\bTODO\b/',                     // Development placeholders
      '/\bFIXME\b/',                    // Development placeholders
      '/I don\'t (know|have)/i',        // AI uncertainty phrases
      '/I cannot (provide|access)/i',   // AI limitation phrases
      '/As an AI/i',                    // AI self-reference
      '/\[placeholder\]/i',             // Explicit placeholders
    ];
  }

  /**
   * Main guardrails method - Full validation of the LLM response.
   *
   * Performs a comprehensive validation of the AI-generated answer, including:
   * - Structural checks (length, encoding, malicious code, JSON structure)
   * - Business content validation (realistic metrics, percentages) - domain-specific when configured
   * - Hallucination detection (suspicious patterns, future dates, impossible values)
   * - Numerical data validation (figures, percentages, currency amounts, math consistency)
   * - (Optional) Source and citation validation
   * - Global confidence score calculation
   * - Final decision (allow, block, manual review, warning) based on validation results
   *
   * @param string $result The AI-generated response to validate
   * @return array Validation results including scores and recommended action
   */
  public static function GuardrailsResult(string $result): array
  {
    self::initLogger();
    $validationResults = [];

    try {
      // 1. Structural validation
      $structuralValidation = self::validateStructure($result);
      $validationResults['structural'] = $structuralValidation;

      // 2. Business content validation
      $contentValidation = self::validateBusinessContent($result);
      $validationResults['content'] = $contentValidation;

      $hallucinationCheck = self::detectHallucinations($result);
      $validationResults['hallucination'] = $hallucinationCheck;

      // 4. Numerical validation for BI metrics
      $numericalValidation = self::validateNumericalData($result);
      $validationResults['numerical'] = $numericalValidation;

      // 5. Source and citation validation
      $sourceValidation = self::validateSources($result);
      $validationResults['sources'] = $sourceValidation;

      // 6. Overall confidence score
      $confidenceScore = self::calculateConfidenceScore($validationResults);
      $validationResults['confidence_score'] = $confidenceScore;

      // 7. Final decision
      $validationResults['is_valid'] = $confidenceScore >= self::CONFIDENCE_THRESHOLD;
      $validationResults['action'] = self::determineAction($confidenceScore, $validationResults);

      // Debug log
      if (self::$debug) {
        self::$securityLogger->logSecurityEvent('Guardrails Validation: ' . json_encode($validationResults), 'info');
      }

      return $validationResults;

    } catch (\Exception $e) {
      self::$securityLogger->logSecurityEvent('Guardrails Error: ' . $e->getMessage(), 'error');

      return [
        'error' => true,
        'message' => CLICSHOPPING::getDef('error_llm_guardrails_validation'),
        'is_valid' => false,
        'action' => 'block'
      ];
    }
  }

  /**
   * Structural validation of the response.
   *
   * Checks the structure of the AI-generated response, including:
   * - Length constraints
   * - UTF-8 encoding validity
   * - Presence of content
   * - Absence of malicious code (e\.g\. scripts)
   * - Valid JSON structure if applicable
   *
   * @param string $result The AI-generated response to validate
   * @return array Validation results with individual checks and a global score
   */
  private static function validateStructure(string $result): array
  {
    $validation = [
      'length_valid' => strlen($result) <= self::MAX_RESPONSE_LENGTH && strlen($result) > 10,
      'encoding_valid' => mb_check_encoding($result, 'UTF-8'),
      'has_content' => !empty(trim($result)),
      'no_malicious_code' => !self::containsMaliciousCode($result),
      'json_structure' => self::validateJsonStructure($result)
    ];

    $validation['score'] = array_sum($validation) / count($validation);

    return $validation;
  }

  /**
   * Checks if the given text contains potentially malicious code.
   *
   * Scans for common attack vectors such as \<script\>, \<iframe\>, javascript: URLs, or onclick attributes.
   *
   * @param string $text The text to scan for malicious code.
   * @return bool True if malicious code is detected, false otherwise.
   */
  private static function containsMaliciousCode(string $text): bool
  {
    $patterns = ['/<script/', '/<iframe/', '/javascript:/', '/onclick=/'];

    foreach ($patterns as $pattern) {
      if (preg_match($pattern, $text))
        return true;
    }

    return false;
  }

  /**
   * Checks if the provided text is a valid JSON structure.
   *
   * @param string $text The text to validate as JSON.
   * @return bool True if the text contains valid JSON, false otherwise.
   */
  private static function validateJsonStructure(string $text): bool
  {
    // If the text contains JSON, check its validity
    if (str_contains($text, '{') || str_contains($text, '[')) {
      return json_last_error() === JSON_ERROR_NONE;
    }

    return true; // No JSON detected
  }

  /**
   * Business Content Validation (domain-agnostic)
   *
   * Validates the business logic and domain-specific content of the AI-generated response.
   * When a domain is active, loads business validation rules from GuardrailsConfig if available.
   * When no domain is configured, uses generic validation.
   *
   * Checks for realistic metrics, valid percentages, and optionally entity references,
   * currency formats, and temporal consistency based on domain configuration.
   *
   * @param string $result The AI-generated response to validate
   * @return array Validation results with individual checks and a global score
   */
  private static function validateBusinessContent(string $result): array
  {
    // Get active domain
    $domain = DomainConfig::getActivities();

    // Initialize validation array
    $validation = [];

    // Load business rules from domain config if available
    $guardrailsConfig = self::resolveGuardrailsConfigClass($domain);
    if ($guardrailsConfig !== null) {
      try {
        if (class_exists($guardrailsConfig) && method_exists($guardrailsConfig, 'getBusinessRules')) {
          $businessRules = $guardrailsConfig::getBusinessRules();

          // Apply domain-specific business rules
          if ($businessRules['validate_metrics'] ?? true) {
            $validation['realistic_metrics'] = self::validateRealisticMetrics($result);
          }

          if ($businessRules['validate_percentages'] ?? true) {
            $validation['percentage_validity'] = self::validatePercentages($result);
          }
        } else {
          // Fallback to default validation if methods not available
          $validation['realistic_metrics'] = self::validateRealisticMetrics($result);
          $validation['percentage_validity'] = self::validatePercentages($result);
        }
      } catch (\Exception $e) {
        // Fallback to generic validation on error
        if (self::$debug) {
          self::$securityLogger->logSecurityEvent(
            'Error loading business rules from GuardrailsConfig: ' . $e->getMessage(),
            'warning'
          );
        }
        $validation['realistic_metrics'] = self::validateRealisticMetrics($result);
        $validation['percentage_validity'] = self::validatePercentages($result);
      }
    } else {
      // Generic validation when no domain configured
      $validation['realistic_metrics'] = self::validateRealisticMetrics($result);
      $validation['percentage_validity'] = self::validatePercentages($result);
    }

    $validation['score'] = array_sum($validation) / count($validation);

    return $validation;
  }

  /**
   * Validates if the business metrics in the AI-generated response are realistic.
   *
   * Checks for suspicious growth percentages (e.g., excessive growth rates).
   * When a domain is active, loads validation patterns from GuardrailsConfig if available.
   * When no domain is configured, uses generic validation.
   *
   * Returns true if metrics are within realistic bounds, false otherwise.
   *
   * @param string $result The AI-generated response to validate.
   * @return bool True if metrics are realistic, false otherwise.
   */
  private static function validateRealisticMetrics(string $result): bool
  {
    // Get active domain
    $domain = DomainConfig::getActivities();

    // Load validation patterns from domain config if available
    $guardrailsConfig = self::resolveGuardrailsConfigClass($domain);
    if ($guardrailsConfig !== null) {
      try {
        if (class_exists($guardrailsConfig) && method_exists($guardrailsConfig, 'getValidationPatterns')) {
          $patterns = $guardrailsConfig::getValidationPatterns();
          $maxGrowth = $patterns['max_growth_percentage'] ?? 500;

          // Validate growth percentages using domain-specific rules
          if (preg_match('/(\d+)%/', $result, $matches)) {
            $percentage = (int) $matches[1];
            return $percentage <= $maxGrowth;
          }

          return true;
        }
      } catch (\Exception $e) {
        // Fallback to generic validation on error
        if (self::$debug) {
          self::$securityLogger->logSecurityEvent(
            'Error loading validation patterns from GuardrailsConfig: ' . $e->getMessage(),
            'warning'
          );
        }
      }
    }

    // Generic validation when no domain configured or domain config not available
    if (preg_match('/(\d+)%/', $result, $matches)) {
      $percentage = (int) $matches[1];
      return $percentage <= 500; // Generic max realistic growth
    }

    return true;
  }

  /**
   * Validates percentages in the AI-generated response.
   *
   * Checks if all percentages are within a realistic range (0% to 500%).
   * Returns true if all percentages are valid, false otherwise.
   *
   * @param string $result The AI-generated response to validate.
   * @return bool True if all percentages are valid, false otherwise.
   */
  private static function validatePercentages(string $result): bool
  {
    preg_match_all('/(\d+(?:[.,]\d+)?)%/', $result, $matches);

    foreach ($matches[1] as $value) {
      $val = (float) str_replace(',', '.', $value);
      if ($val < 0 || $val > 500) {
        return false;
      }
    }

    return true;
  }

  /**
   * Specific Hallucination Detection
   *
   * Detects suspicious patterns in the LLM response that may indicate hallucinations,
   * such as unrealistic sales figures, future dates, or impossible values.
   * Returns details about detected patterns, future dates, impossible values,
   * a reversed score, and a suspect flag.
   *
   * Uses domain-specific patterns loaded from the active domain app.
   */
  private static function detectHallucinations(string $result): array
  {
    $suspiciousCount = 0;
    $detectedPatterns = [];

    foreach (self::$suspiciousPatterns as $pattern) {
      if (preg_match($pattern, $result, $matches)) {
        $suspiciousCount++;
        $detectedPatterns[] = $matches[0];
      }
    }

    // Check for impossible dates
    $futureDates = self::detectFutureDates($result);
    $impossibleValues = self::detectImpossibleValues($result);

    return [
      'suspicious_patterns_count' => $suspiciousCount,
      'detected_patterns' => $detectedPatterns,
      'future_dates' => $futureDates,
      'impossible_values' => $impossibleValues,
      'score' => 1 - min(1, $suspiciousCount / 3), // Inverted score
      'is_suspect' => $suspiciousCount > 2 || !empty($futureDates) || !empty($impossibleValues)
    ];
  }

  /**
   * Detects future dates in the AI-generated response.
   *
   * Scans the response for any references to future dates or time periods.
   * Returns an array of detected future dates or an empty array if none found.
   *
   * @param string $result The AI-generated response to scan for future dates.
   * @return array List of detected future dates.
   */
  private static function detectFutureDates(string $result): array
  {
    $futureDates = [];
    // Future date detection logic
    // Implementation according to specific needs
    return $futureDates;
  }

  /**
   * Detects impossible values in the AI-generated response.
   *
   * Scans the response for any values that are unrealistic or impossible
   * in the business context, such as percentages over 1000% or
   * other nonsensical numerical values.
   *
   * @param string $result The AI-generated response to scan for impossible values.
   * @return array List of detected impossible values.
   */
  private static function detectImpossibleValues(string $result): array
  {
    $impossibleValues = [];

    // Detect impossible values (e.g., percentages > 100% for certain contexts)
    if (preg_match_all('/(\d+(?:\.\d+)?)%/', $result, $matches)) {
      foreach ($matches[1] as $value) {
        if ((float) $value > 1000) { // Absurd percentage
          $impossibleValues[] = $value . '%';
        }
      }
    }

    return $impossibleValues;
  }

  /**
   * Numeric Data Validation
   *
   * Validates numerical data in the AI-generated response.
   * Extracts numbers from the text and checks for:
   * - Realistic sales figures
   * - Valid percentage ranges
   * - Mathematical consistency (e\.g\. totals vs subtotals)
   * - Plausible currency amounts
   *
   * @param string $result The AI-generated response to validate
   * @return array Validation results with individual checks and a global score
   */
  private static function validateNumericalData(string $result): array
  {
    // Extract numbers from the text
    preg_match_all('/\d+(?:[,.]\d+)*/', $result, $numbers);

    $validation = [
      'realistic_sales_figures' => self::validateSalesFigures($numbers[0] ?? []),
      'percentage_range' => self::validatePercentageRange($result),
      'mathematical_consistency' => self::validateMathConsistency($result),
      'currency_amounts' => self::validateCurrencyAmounts($result)
    ];

    $validation['score'] = array_sum($validation) / count($validation);
    return $validation;
  }

  /**
   * Validates sales figures in the AI-generated response.
   *
   * Checks if the sales figures are realistic and within acceptable limits.
   * Returns true if all figures are valid, false otherwise.
   *
   * @param array $numbers Array of sales figures extracted from the response.
   * @return bool True if all sales figures are valid, false otherwise.
   */
  private static function validateSalesFigures(array $numbers): bool
  {
    foreach ($numbers as $n) {
      $val = (float) str_replace([',', ' '], '', $n);
      if ($val > 10000000) {
        return false;
      }
    }

    return true;
  }

  /**
   * Validates percentage ranges in the AI-generated response.
   *
   * Checks if all percentages are within the range of 0% to 1000%.
   * Returns true if all percentages are valid, false otherwise.
   *
   * @param string $result The AI-generated response to validate.
   * @return bool True if all percentages are valid, false otherwise.
   */
  private static function validatePercentageRange(string $result): bool
  {
    preg_match_all('/(\d+(?:[.,]\d+)?)%/', $result, $matches);
    foreach ($matches[1] as $value) {
      $val = (float) str_replace(',', '.', $value);
      if ($val < 0 || $val > 1000) {
        return false;
      }
    }

    return true;
  }

  /**
   * Validates mathematical consistency in the AI-generated response.
   *
   * Checks if the totals and subtotals in the response are consistent.
   * Returns true if the math is consistent, false otherwise.
   *
   * @param string $result The AI-generated response to validate.
   * @return bool True if the math is consistent, false otherwise.
   */
  private static function validateMathConsistency(string $result): bool
  {
    // Simple heuristic: equality between subtotals and totals
    // Example: "Total: 100€, Product A: 60€, Product B: 40€"
    if (preg_match_all('/(\d+(?:[.,]\d+)?)\s*(€|\$)?/', $result, $matches)) {
      $values = array_map(fn($v) => (float) str_replace(',', '.', $v), $matches[1]);

      if (count($values) >= 3) {
        $sum = array_sum(array_slice($values, 1));
        $delta = abs($values[0] - $sum);

        return $delta < 1.0;
      }
    }

    return true;
  }

  /**
   * Validates currency amounts in the AI-generated response.
   *
   * Checks if all currency amounts are within a realistic range (e\.g\. 0 to 1,000,000).
   * Returns true if all amounts are valid, false otherwise.
   *
   * @param string $result The AI-generated response to validate.
   * @return bool True if all currency amounts are valid, false otherwise.
   */
  private static function validateCurrencyAmounts(string $result): bool
  {
    preg_match_all('/[€$]\s*(\d+(?:[.,]\d+)?)/', $result, $matches);

    foreach ($matches[1] as $value) {
      $amount = (float) str_replace(',', '.', $value);
      if ($amount < 0 || $amount > 1000000) {
        return false;
      }
    }

    return true;
  }

  /**
   * Validates sources and citations in the AI-generated response.
   *
   * Checks for the presence, quality and authenticity of sources.
   * Returns detailed validation results with score.
   *
   * @param string $result The AI-generated response to validate.
   * @return array Validation results with source analysis.
   */
  private static function validateSources(string $result): array
  {
    $validation = [
      'has_sources' => false,
      'source_count' => 0,
      'valid_citations' => 0,
      'suspicious_sources' => 0,
      'score' => 0.0
    ];

    // Source detection patterns (English - LLM processing in English)
    $sourcePatterns = [
      '/source\s*:\s*([^\n]+)/i',
      '/\(see\s+([^)]+)\)/i',
      '/\[([^\]]+)\]/',
      '/according\s+to\s+([^,\.]+)/i',
      '/based\s+on\s+([^,\.]+)/i',
      '/documents?\s+([0-9]+)/i',
      '/reference\s+([0-9]+)/i',
      '/cited\s+in\s+([^,\.]+)/i'
    ];

    $totalSources = 0;
    $validSources = 0;

    foreach ($sourcePatterns as $pattern) {
      if (preg_match_all($pattern, $result, $matches)) {
        $totalSources += count($matches[1]);

        foreach ($matches[1] as $source) {
          $source = trim($source);
          // Check if the source appears valid
          if (
            strlen($source) > 3 &&
            !preg_match('/^(test|exemple|fictif|imaginaire)/i', $source) &&
            !preg_match('/^(lorem|ipsum|placeholder)/i', $source)
          ) {
            $validSources++;
          } else {
            $validation['suspicious_sources']++;
          }
        }
      }
    }

    $validation['has_sources'] = $totalSources > 0;
    $validation['source_count'] = $totalSources;
    $validation['valid_citations'] = $validSources;

    // Calculate score
    if ($totalSources == 0) {
      $validation['score'] = 0.3;
    } else {
      $validRatio = $validSources / $totalSources;
      $validation['score'] = min(1.0, $validRatio * 0.8 + 0.2);
    }

    return $validation;
  }

  /**
   * Calculates the overall confidence score for the LLM response validation.
   *
   * Aggregates the scores from different validation categories (structural, content, hallucination, numerical, sources)
   * using predefined weights. Returns a float between 0.0 and 1.0 representing the global confidence in the response.
   *
   * @param array $validationResults Array of validation results for each category.
   * @return float Global confidence score (0.0 to 1.0).
   */
  private static function calculateConfidenceScore(array $validationResults): float
  {
    $totalScore = 0;
    foreach (self::WEIGHTS as $category => $weight) {
      if (isset($validationResults[$category]['score'])) {
        $totalScore += $validationResults[$category]['score'] * $weight;
      }
    }

    // Apply minimum confidence threshold
    return min(1.0, max(self::MIN_CONFIDENCE_SCORE, $totalScore));
  }

  /**
   * Determines the action to take based on the confidence score.
   *
   * Returns one of: 'allow', 'allow_with_warning', 'manual_review', or 'block'
   * depending on the provided score and validation results.
   *
   * @param float $confidenceScore The global confidence score for the LLM response.
   * @param array $validationResults The array of validation results for each category.
   * @return string The recommended action.
   */
  private static function determineAction(float $confidenceScore, array $validationResults): string
  {
    if ($confidenceScore >= 0.9) {
      return 'allow';
    } elseif ($confidenceScore >= 0.7) {
      return 'allow_with_warning';
    } elseif ($confidenceScore >= 0.5) {
      return 'manual_review';
    } else {
      return 'block';
    }
  }

  /**
   * Resolve the GuardrailsConfig class for the active domain.
   *
   * @param string|null $domain
   * @return string|null
   */
  private static function resolveGuardrailsConfigClass(?string $domain): ?string
  {
    $module = DomainFields::getModuleName($domain);
    if ($module !== null && $module !== '') {
      $className = 'ClicShopping\\Apps\\AI\\' . $module . '\\Classes\\ClicShoppingAdmin\\GuardrailsConfig';
      if (class_exists($className)) {
        return $className;
      }
    }

    // Fallback to Ecommerce guardrails when domain-specific config is missing
    $fallback = 'ClicShopping\\Apps\\AI\\Ecommerce\\Classes\\ClicShoppingAdmin\\GuardrailsConfig';
    return class_exists($fallback) ? $fallback : null;
  }
}
