<?php
/**
 * @copyright 2008 - https://www.clicshopping.org
 * @Brand : ClicShoppingAI(TM) at Inpi all right Reserved
 * @Licence GPL 2 & MIT
 * @Info : https://www.clicshopping.org/forum/trademark/
 */

namespace ClicShopping\AI\DomainsAI\WebSearch\Logger;


use ClicShopping\OM\Registry;
use ClicShopping\OM\Hash;
use ClicShopping\OM\HTTP;

use ClicShopping\AI\Security\InputValidator;
use ClicShopping\AI\Security\SecurityLogger;
use ClicShopping\Apps\Configuration\Administrators\Classes\ClicShoppingAdmin\AdministratorAdmin;
use DateTimeImmutable;

/**
 * WebSearchLogger Class
 *
 * Manages web search query logging and results storage.
 * Separates web_search data from internal RAG data (gpt table).
 */

class WebSearchLogger
{
  private $db;
  private SecurityLogger $logger;
  private bool $debug;

  /**
   * Constructor
   */
  public function __construct()
  {
    $this->db = Registry::get('Db');
    $this->logger = new SecurityLogger();
    $this->debug = defined('CLICSHOPPING_APP_CHATGPT_RA_DEBUG_RAG_MANAGER') && CLICSHOPPING_APP_CHATGPT_RA_DEBUG_RAG_MANAGER === 'True';
  }

  /**
   * Saves a complete web search request with three-mode support
   *
   * @param string $query Original query
   * @param string $translatedQuery Query translated to English
   * @param array $intentData Intent data (from SemanticAgent::classifySearchIntent)
   * @param array $searchResults Results from WebSearchTool or unified engine
   * @param string $responseSummary Summary generated by LLM
   * @param array $metadata Additional metadata including mode_type, mode_metadata, engines_used
   * @return int|false ID of saved request or false on failure
   */
  public function saveWebSearchRequest(
    string $query,
    string $translatedQuery,
    array $intentData,
    array $searchResults,
    string $responseSummary,
    array $metadata = []
  ): int|false {
    try {
      // Validate input data
      $validatedQuery = InputValidator::validateParameter(
        $query,
        'string',
        '',
        ['maxLength' => 2048, 'escape' => true]
      );

      $validatedTranslated = InputValidator::validateParameter(
        $translatedQuery,
        'string',
        '',
        ['maxLength' => 2048, 'escape' => true]
      );

      $validatedSummary = InputValidator::validateParameter(
        $responseSummary,
        'string',
        '',
        ['maxLength' => 8192, 'escape' => true]
      );

      $validatedUserAdmin = InputValidator::validateParameter(
        AdministratorAdmin::getUserAdmin(),
        'string',
        'system',
        [
          'maxLength' => 255,
          'pattern' => '/^[a-zA-Z0-9_\-\.\s]+$/'
        ]
      );

      // Calculate quality score
      $qualityScore = $this->calculateQualityScore($searchResults);

      // Audit trail
      $timestamp = (new DateTimeImmutable())->format('Y-m-d H:i:s');
      $auditPayload = [
        'session' => [
          'id' => session_id(),
          'ip' => HTTP::getIpAddress() ?? null,
          'user_agent' => $_SERVER['HTTP_USER_AGENT'] ?? null,
        ],
        'intent' => $intentData,
        'search_metadata' => $searchResults['metadata'] ?? [],
        'execution_time' => $metadata['execution_time'] ?? 0,
        'api_cost' => $metadata['api_cost'] ?? 0,
        'cached' => $metadata['cached'] ?? false,
        'hash' => Hash::encryptDatatext($validatedUserAdmin . session_id() . $timestamp),
      ];

      // Prepare data with three-mode support
      $array_sql = [
        'query' => $validatedQuery,
        'translated_query' => $validatedTranslated,
        'intent' => $intentData['intent'] ?? 'EXTERNAL_WEB',
        'intent_confidence' => $intentData['confidence'] ?? 0.0,
        'search_engine' => $searchResults['metadata']['search_engine'] ?? 'serpapi',
        'mode_type' => $metadata['mode_type'] ?? null,
        'mode_metadata' => isset($metadata['mode_metadata']) ? json_encode($metadata['mode_metadata'], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) : null,
        'results_count' => count($searchResults['items'] ?? []),
        'response_summary' => $validatedSummary,
        'quality_score' => $qualityScore,
        'cached' => $metadata['cached'] ?? false ? 1 : 0,
        'cached_in_rag' => $metadata['cached_in_rag'] ?? false ? 1 : 0,
        'execution_time' => $metadata['execution_time'] ?? 0.0,
        'api_cost' => $metadata['api_cost'] ?? 0.0,
        'user_admin' => $validatedUserAdmin,
        'session_id' => session_id(),
        'ip_address' => HTTP::getIpAddress(),
        'date_added' => 'now()',
        'audit_data' => json_encode($auditPayload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES),
      ];

      // Insert into rag_web_search_requests
      $this->db->save('rag_web_search_requests', $array_sql);
      $requestId = $this->db->lastInsertId();

      if ($this->debug) {
        $this->logger->logSecurityEvent(
          "Web search request saved (ID: {$requestId})",
          'info'
        );
      }

      // Save individual results
      if (!empty($searchResults['items'])) {
        $this->saveWebSearchResults($requestId, $searchResults['items']);
      }

      // Update statistics
      $this->updateDailyStats($metadata);

      return $requestId;

    } catch (\Exception $e) {
      $this->logger->logSecurityEvent(
        "Error saving web search request: " . $e->getMessage(),
        'error'
      );

      // Do not propagate error to avoid blocking response
      error_log("WebSearchLogger error: " . $e->getMessage());

      return false;
    }
  }

  /**
   * Saves individual result items with three-mode support
   *
   * @param int $requestId Parent request ID
   * @param array $items Result items (organic, shopping, or ai_overview)
   * @return int Number of items saved
   */
  private function saveWebSearchResults(int $requestId, array $items): int
  {
    $savedCount = 0;

    try {
      foreach ($items as $item) {
        $array_sql = [
          'search_request_id' => $requestId,
          'position' => $item['position'] ?? 0,
          'title' => substr($item['title'] ?? '', 0, 500),
          'link' => substr($item['link'] ?? '', 0, 500),
          'snippet' => substr($item['snippet'] ?? '', 0, 1000),
          'source_domain' => $item['source'] ?? 'unknown',
          'relevance_score' => $item['relevance_score'] ?? 0.0,
          'result_type' => $item['result_type'] ?? 'organic',
          'price' => $item['extracted_price'] ?? null,
          'old_price' => $item['extracted_old_price'] ?? null,
          'thumbnail' => isset($item['thumbnail']) ? substr($item['thumbnail'], 0, 500) : null,
          'product_link' => isset($item['product_link']) ? substr($item['product_link'], 0, 500) : null,
          'date_added' => 'now()',
        ];

        $this->db->save('rag_web_search_results', $array_sql);
        $savedCount++;
      }

      if ($this->debug) {
        $this->logger->logSecurityEvent(
          "Saved {$savedCount} web search result items",
          'info'
        );
      }

    } catch (\Exception $e) {
      $this->logger->logSecurityEvent(
        "Error saving web search results: " . $e->getMessage(),
        'error'
      );
    }

    return $savedCount;
  }

  /**
   * Updates daily statistics
   *
   * @param array $metadata Request metadata
   */
  private function updateDailyStats(array $metadata): void
  {
    try {
      // 🔧 FIX (2026-05-07): Define $today variable before use
      $today = date('Y-m-d');
      
      // Get existing stats
      $sql = "SELECT * FROM :table_rag_web_search_stats WHERE date = :date";
      $stmt = $this->db->prepare($sql);
      $stmt->bindValue(':date', $today);
      $stmt->execute();
      $stats = $stmt->fetch();

      if ($stats) {
        // Update existing
        // 🔧 FIX (2026-05-07): Fixed WHERE clause (was update_at, should be date)
        $sql = "UPDATE :table_rag_web_search_stats 
                SET total_searches = total_searches + 1,
                    cache_hits = cache_hits + :cached,
                    api_calls = api_calls + :api_call,
                    total_api_cost = total_api_cost + :cost,
                    avg_response_time = (avg_response_time * (total_searches - 1) + :exec_time) / total_searches
                WHERE date = :date";

        $stmt = $this->db->prepare($sql);
        $stmt->execute([
          'cached' => $metadata['cached'] ?? false ? 1 : 0,
          'api_call' => $metadata['cached'] ?? false ? 0 : 1,
          'cost' => $metadata['api_cost'] ?? 0.0,
          'exec_time' => $metadata['execution_time'] ?? 0.0,
          'date' => $today,
        ]);

      } else {
        // Create new entry
        // 🔧 FIX (2026-05-07): Added missing 'date' column in INSERT
        $array_sql = [
          'date' => $today,
          'created_at' => 'now()',
          'total_searches' => 1,
          'cache_hits' => $metadata['cached'] ?? false ? 1 : 0,
          'api_calls' => $metadata['cached'] ?? false ? 0 : 1,
          'failed_searches' => 0,
          'avg_response_time' => $metadata['execution_time'] ?? 0.0,
          'total_api_cost' => $metadata['api_cost'] ?? 0.0,
          'unique_queries' => 1,
          'price_comparisons' => 0,
        ];

        $this->db->save('rag_web_search_stats', $array_sql);
      }

    } catch (\Exception $e) {
      // Log but do not block
      if ($this->debug) {
        $this->logger->logSecurityEvent(
          "Error updating daily stats: " . $e->getMessage(),
          'warning'
        );
      }
    }
  }

  /**
   * Logs search operation to clic_rag_statistics table with three-mode metadata
   *
   * @param string $query Original query
   * @param array $metadata Three-mode metadata including mode_type, engines_used, routing_method
   * @param bool $success Whether the search succeeded
   * @param float $responseTime Total execution time
   * @return bool Success status
   */
  public function logToRagStatistics(
    string $query,
    array $metadata,
    bool $success,
    float $responseTime
  ): bool {
    try {
      // Validate input
      $validatedQuery = InputValidator::validateParameter(
        $query,
        'string',
        '',
        ['maxLength' => 2048, 'escape' => true]
      );

      // Build mode-specific metadata
      $modeMetadata = [
        'mode_type' => $metadata['mode_type'] ?? 'legacy',
        'engines_used' => $metadata['engines_used'] ?? [],
        'routing_method' => $metadata['routing_method'] ?? 'direct',
        'hybrid_combination' => $metadata['hybrid_combination'] ?? false,
      ];

      // Add mode-specific execution times if available
      if (isset($metadata['mode_a_execution_time'])) {
        $modeMetadata['mode_a_execution_time'] = $metadata['mode_a_execution_time'];
      }
      if (isset($metadata['mode_b_execution_time'])) {
        $modeMetadata['mode_b_execution_time'] = $metadata['mode_b_execution_time'];
      }
      if (isset($metadata['mode_c_execution_time'])) {
        $modeMetadata['mode_c_execution_time'] = $metadata['mode_c_execution_time'];
      }

      // Add result counts
      if (isset($metadata['total_shopping_results'])) {
        $modeMetadata['total_shopping_results'] = $metadata['total_shopping_results'];
      }
      if (isset($metadata['total_organic_results'])) {
        $modeMetadata['total_organic_results'] = $metadata['total_organic_results'];
      }

      // Prepare data for rag_statistics
      $array_sql = [
        'query_type' => 'web_search',
        'query' => $validatedQuery,
        'success' => $success ? 1 : 0,
        'response_time' => $responseTime,
        'metadata' => json_encode($modeMetadata, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES),
        'created_at' => 'now()',
      ];

      $this->db->save('rag_statistics', $array_sql);

      if ($this->debug) {
        $this->logger->logSecurityEvent(
          "Logged web search to rag_statistics (mode: {$modeMetadata['mode_type']})",
          'info'
        );
      }

      return true;

    } catch (\Exception $e) {
      $this->logger->logSecurityEvent(
        "Error logging to rag_statistics: " . $e->getMessage(),
        'error'
      );

      // Do not propagate error
      return false;
    }
  }

  /**
   * Calculates quality score for search results
   *
   * @param array $results Search results
   * @return float Score (0-1)
   */
  private function calculateQualityScore(array $results): float
  {
    $score = 0.5;

    // Featured snippet
    if (isset($results['featured_snippet']) && !empty($results['featured_snippet']['answer'])) {
      $score += 0.2;
    }

    // Relevant results
    $relevantCount = 0;
    foreach ($results['items'] ?? [] as $item) {
      if (($item['relevance_score'] ?? 0) > 0.7) {
        $relevantCount++;
      }
    }
    $score += min($relevantCount * 0.1, 0.3);

    return min($score, 1.0);
  }

  /**
   * Deletes old entries according to retention policy
   *
   * @param int $daysToKeep Number of days to keep
   * @return int Number of entries deleted
   */
  public function cleanOldSearches(int $daysToKeep = 90): int
  {
    try {
      // Delete individual results first (no FK)
      $sql = "DELETE wsr FROM :table_rag_web_search_results wsr
              INNER JOIN :table_rag_web_search_requests wsreq ON wsr.search_request_id = wsreq.id
              WHERE wsreq.date_added < DATE_SUB(NOW(), INTERVAL :days DAY)
                AND wsreq.cached_in_rag = 0";

      $stmt = $this->db->prepare($sql);
      $stmt->bindInt('days', $daysToKeep);
      $stmt->execute();
      $deletedResults = $stmt->rowCount();

      // Delete main requests
      $sql = "DELETE FROM :table_rag_web_search_requests 
              WHERE date_added < DATE_SUB(NOW(), INTERVAL :days DAY)
                AND cached_in_rag = 0";

      $stmt = $this->db->prepare($sql);
      $stmt->bindInt('days', $daysToKeep);
      $stmt->execute();
      $deletedRequests = $stmt->rowCount();

      if ($this->debug) {
        $this->logger->logSecurityEvent(
          "Cleaned {$deletedRequests} old web search requests and {$deletedResults} results",
          'info'
        );
      }

      return $deletedRequests;

    } catch (\Exception $e) {
      $this->logger->logSecurityEvent(
        "Error cleaning old searches: " . $e->getMessage(),
        'error'
      );
      return 0;
    }
  }

  /**
   * Gets global statistics
   *
   * @param int $days Number of days to analyze
   * @return array Statistics
   */
  public function getStats(int $days = 30): array
  {
    try {
      $sql = "SELECT 
                COUNT(*) as total_searches,
                SUM(cached) as cached_hits,
                SUM(CASE WHEN cached = 0 THEN 1 ELSE 0 END) as api_calls,
                AVG(execution_time) as avg_execution_time,
                AVG(quality_score) as avg_quality_score,
                SUM(api_cost) as total_api_cost,
                SUM(cached_in_rag) as rag_stored_count
              FROM :table_rag_web_search_requests
              WHERE date_added >= DATE_SUB(NOW(), INTERVAL :days DAY)";

      $stmt = $this->db->prepare($sql);
      $stmt->execute(['days' => $days]);
      $stats = $stmt->fetch();

      $totalSearches = (int)$stats['total_searches'];
      $cachedHits = (int)$stats['cached_hits'];
      $cacheHitRate = $totalSearches > 0 ? ($cachedHits / $totalSearches) * 100 : 0;

      return [
        'period_days' => $days,
        'total_searches' => $totalSearches,
        'cached_hits' => $cachedHits,
        'api_calls' => (int)$stats['api_calls'],
        'cache_hit_rate' => round($cacheHitRate, 2) . '%',
        'avg_execution_time' => round((float)$stats['avg_execution_time'], 3) . 's',
        'avg_quality_score' => round((float)$stats['avg_quality_score'], 2),
        'total_api_cost' => round((float)$stats['total_api_cost'], 4) . ' USD',
        'rag_stored_count' => (int)$stats['rag_stored_count'],
      ];

    } catch (\Exception $e) {
      $this->logger->logSecurityEvent(
        "Error getting stats: " . $e->getMessage(),
        'error'
      );

      return [];
    }
  }

  /**
   * Gets three-mode statistics
   *
   * @param int $days Number of days to analyze
   * @return array Mode-specific statistics
   */
  public function getThreeModeStats(int $days = 30): array
  {
    try {
      $sql = "SELECT 
                mode_type,
                COUNT(*) as total_searches,
                AVG(execution_time) as avg_execution_time,
                AVG(quality_score) as avg_quality_score,
                SUM(results_count) as total_results
              FROM :table_rag_web_search_requests
              WHERE date_added >= DATE_SUB(NOW(), INTERVAL :days DAY)
                AND mode_type IS NOT NULL
              GROUP BY mode_type";

      $stmt = $this->db->prepare($sql);
      $stmt->execute(['days' => $days]);
      $modeStats = $stmt->fetchAll();

      $stats = [
        'period_days' => $days,
        'modes' => [],
      ];

      foreach ($modeStats as $modeStat) {
        $stats['modes'][$modeStat['mode_type']] = [
          'total_searches' => (int)$modeStat['total_searches'],
          'avg_execution_time' => round((float)$modeStat['avg_execution_time'], 3) . 's',
          'avg_quality_score' => round((float)$modeStat['avg_quality_score'], 2),
          'total_results' => (int)$modeStat['total_results'],
        ];
      }

      return $stats;

    } catch (\Exception $e) {
      $this->logger->logSecurityEvent(
        "Error getting three-mode stats: " . $e->getMessage(),
        'error'
      );

      return ['period_days' => $days, 'modes' => []];
    }
  }

  /**
   * Logs intent routing decision
   *
   * @param string $query Original query
   * @param array $intent Detected intent structure
   * @param string $routingMethod Method used (llm|pattern)
   * @param float $confidence Confidence score
   * @return bool Success status
   */
  public function logIntentRouting(
    string $query,
    array $intent,
    string $routingMethod,
    float $confidence
  ): bool {
    try {
      if ($this->debug) {
        $this->logger->logSecurityEvent(
          "Intent routing: query='{$query}', method={$routingMethod}, confidence={$confidence}, intent=" . json_encode($intent),
          'info'
        );
      }

      return true;

    } catch (\Exception $e) {
      $this->logger->logSecurityEvent(
        "Error logging intent routing: " . $e->getMessage(),
        'error'
      );

      return false;
    }
  }

  /**
   * Logs price tracking operation
   *
   * @param int|null $productId Product ID (null if unmatched)
   * @param string $competitorSource Competitor source
   * @param float $price Price value
   * @param string $engineType Engine type (google_shopping|rag_websearch)
   * @param array $metadata Additional metadata
   * @return bool Success status
   */
  public function logPriceTracking(
    ?int $productId,
    string $competitorSource,
    float $price,
    string $engineType,
    array $metadata = []
  ): bool {
    try {
      if ($this->debug) {
        $matchStatus = $productId ? 'matched' : 'unmatched';
        $this->logger->logSecurityEvent(
          "Price tracking: product_id={$productId}, source={$competitorSource}, price={$price}, engine={$engineType}, status={$matchStatus}",
          'info'
        );
      }

      return true;

    } catch (\Exception $e) {
      $this->logger->logSecurityEvent(
        "Error logging price tracking: " . $e->getMessage(),
        'error'
      );

      return false;
    }
  }

  /**
   * Logs cache storage operation
   *
   * @param string $query Query being cached
   * @param float $qualityScore Quality score
   * @param string $cacheFormat Cache format (json_v2.0|legacy_text)
   * @param bool $success Storage success status
   * @return bool Success status
   */
  public function logCacheStorage(
    string $query,
    float $qualityScore,
    string $cacheFormat,
    bool $success
  ): bool {
    try {
      if ($this->debug) {
        $status = $success ? 'success' : 'failed';
        $this->logger->logSecurityEvent(
          "Cache storage: query='{$query}', quality_score={$qualityScore}, format={$cacheFormat}, status={$status}",
          'info'
        );
      }

      return true;

    } catch (\Exception $e) {
      $this->logger->logSecurityEvent(
        "Error logging cache storage: " . $e->getMessage(),
        'error'
      );

      return false;
    }
  }

  /**
   * Logs info message
   *
   * @param string $message Log message
   * @param array $context Context data
   */
  public function logInfo(string $message, array $context = []): void
  {
    try {
      if ($this->debug) {
        $contextStr = !empty($context) ? ' | Context: ' . json_encode($context) : '';
        $this->logger->logSecurityEvent($message . $contextStr, 'info');
      }
    } catch (\Exception $e) {
      // Silently fail to avoid blocking execution
      error_log("WebSearchLogger::logInfo error: " . $e->getMessage());
    }
  }

  /**
   * Logs warning message
   *
   * @param string $message Log message
   * @param array $context Context data
   */
  public function logWarning(string $message, array $context = []): void
  {
    try {
      $contextStr = !empty($context) ? ' | Context: ' . json_encode($context) : '';
      $this->logger->logSecurityEvent($message . $contextStr, 'warning');
    } catch (\Exception $e) {
      // Silently fail to avoid blocking execution
      error_log("WebSearchLogger::logWarning error: " . $e->getMessage());
    }
  }

  /**
   * Logs error message
   *
   * @param string $message Log message
   * @param array $context Context data
   */
  public function logError(string $message, array $context = []): void
  {
    try {
      $contextStr = !empty($context) ? ' | Context: ' . json_encode($context) : '';
      $this->logger->logSecurityEvent($message . $contextStr, 'error');
    } catch (\Exception $e) {
      // Silently fail to avoid blocking execution
      error_log("WebSearchLogger::logError error: " . $e->getMessage());
    }
  }
}